"""Writes the repository of analyses: one markdown file per launch, plus an index."""
from __future__ import annotations

from datetime import date
from pathlib import Path

from .config import REPORTS_DIR, ROOT
from .dedupe import Entry, Registry
from .models import Analysis
from .render import to_markdown


def write_report(a: Analysis, run_date: date) -> Path:
    folder = REPORTS_DIR / run_date.strftime("%Y") / run_date.strftime("%m")
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f"{run_date.isoformat()}-{a.slug()}.md"
    path.write_text(to_markdown(a, run_date))
    return path


def record(registry: Registry, a: Analysis, run_date: date, report_path: Path) -> Entry:
    from .dedupe import make_key

    entry = Entry(
        key=make_key(a.company, a.product_name),
        company=a.company,
        product_name=a.product_name,
        launch_date=a.launch_date,
        analyzed_on=run_date.isoformat(),
        report_path=str(report_path.relative_to(ROOT)),
        one_liner=a.one_liner,
    )
    registry.add(entry)
    registry.save()
    return entry


def write_index(registry: Registry) -> Path:
    lines = [
        "# Launch Teardown Archive",
        "",
        f"{len(registry.entries)} analyses. Newest first. Generated by the daily agent.",
        "",
        "| Date | Company | Product / feature | Summary |",
        "|---|---|---|---|",
    ]
    for e in sorted(registry.entries, key=lambda x: x.analyzed_on, reverse=True):
        summary = (e.one_liner or "").replace("|", "\\|")[:160]
        lines.append(
            f"| {e.analyzed_on} | {e.company} | [{e.product_name}]({e.report_path}) | {summary} |"
        )
    path = REPORTS_DIR / "README.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return path
